USE ROLE ACCOUNTADMIN;

CREATE ROLE sftp_role;

CREATE DATABASE IF NOT EXISTS sftp_db;
GRANT OWNERSHIP ON DATABASE sftp_db TO ROLE sftp_role COPY CURRENT GRANTS;

CREATE OR REPLACE WAREHOUSE sftp_warehouse WITH
  WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE sftp_warehouse TO ROLE sftp_role;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE sftp_role;

CREATE COMPUTE POOL sftp_compute_pool
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;
GRANT USAGE, MONITOR ON COMPUTE POOL sftp_compute_pool TO ROLE sftp_role;

GRANT ROLE sftp_role TO USER BCULBERSON;

USE ROLE sftp_role;
USE DATABASE sftp_db;
USE WAREHOUSE sftp_warehouse;

CREATE SCHEMA sftp_schema;
CREATE IMAGE REPOSITORY IF NOT EXISTS sftp_repository;
CREATE OR REPLACE STAGE sftp_stage ENCRYPTION = (type = 'SNOWFLAKE_SSE');

SHOW IMAGE REPOSITORIES;
